### ISSUE TITLE
Implementation for Covariates Assisted Spectual Clustering

### ISSUE THREAD

**Issue by jerryyao120-ndd** [microsoft/graspologic#286] opened 2019-11-11 08:04 UTC
https://academic.oup.com/biomet/article/104/2/361/3074977
This paper introduced the CASC method.
R implementation already available, I'm trying to implement it into python.
![image](https://user-images.githubusercontent.com/55103784/68570971-dca50e00-042f-11ea-9c3d-c8768096c790.png)
![image](https://user-images.githubusercontent.com/55103784/68570983-e3cc1c00-042f-11ea-9478-cc89fb4ea935.png)

## Expected Behavior
Tell us what should happen

## Actual Behavior
Tell us what happens instead

## Template Code
```GraSPy
Paste the template code (ideally a minimal example) that causes the issue

```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception

```

## Your Environment
* Python version:
* GraSPy version:

**Comment by bdpedigo** [comment] 2020-10-02 14:16
duplicate of #134

**Closed by bdpedigo** 2020-10-02 14:16 UTC
