### ISSUE TITLE
[BUG] BeartypeDecorHintPepDeprecatedWarning in Python >=3.9.0

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#870] opened 2021-11-01 14:49 UTC
See e.g. the below. 
I think this is just because for typing we're using `typing.List` and `typing.Tuple` rather than just `list` and `tuple`. The versions from the `typing` module are soon-to-be deprecated as per [PEP 585](https://www.python.org/dev/peps/pep-0585/).

Should be an easy fix; just replace every instance of `typing.List` and `typing.Tuple` with `list` and `tuple`. Maybe there are some more generics in the typing module that will need to be replaced as well.

<img width="1626" alt="Screen Shot 2021-11-01 at 10 46 13 AM" src="https://user-images.githubusercontent.com/12386450/139690391-df1e2e9d-ff8a-4747-86b5-50b37739b964.png">

**Comment by bdpedigo** [comment] 2021-11-01 16:31
duplicate of https://github.com/microsoft/graspologic/issues/855

**Closed by bdpedigo** 2021-11-01 16:31 UTC
Labels: bug, good first issue
