### ISSUE TITLE
Fix matplotlib version requirement

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#809] opened 2021-07-11 17:16 UTC
currently we have `matplotlib>=3.0.0,<=3.3.0`.
Matplotlib >= 3.4.0 has some nice features, like `supxtitle`.

Is there a reason we still clip the version?
If not, see #810

**Comment by bdpedigo** [comment] 2021-07-19 03:33
closing cause duplicate of https://github.com/microsoft/graspologic/issues/726 (but would love to have this fixed, thanks for the PR)

**Closed by bdpedigo** 2021-07-19 03:33 UTC
Labels: bug
